### ISSUE TITLE
엔티티 개발

### ISSUE THREAD

**Issue by rookedsysc** [ccondae/api#8]
## Goal 

연관관계 생각해서 엔티티 개발 

## Reference 

- 

## Todo 

- [x] Question Entity 개발
- [x] Comment Entity 개발
- [x] QuestionCategory Entity 개발
- [x] SQL 작성
